# Array Creation in NumPy

In [2]:
# Experiment No. : 05

In [4]:
# Aim: To perform operation of Array Creation in NumPy

In [6]:
# Date: 02/08/2024

In [8]:
# Roll No. : 05

In [10]:
# Section : B

In [12]:
#Subject: ET - 1

In [14]:
import numpy as np

In [16]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

[1 2 3 4 5]


In [18]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [20]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)

[0 2 4 6 8]


In [24]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.02127755 0.32696759 0.11888167]
 [0.69291925 0.6376354  0.29101225]
 [0.01784228 0.55392636 0.73312699]]
